### ISSUE TITLE
Is there a way to use this in nodered?

### ISSUE THREAD

**Issue by JuniorGamingTime** [ncpierson/google-translate-tts#2]
I used to use an old google-tts but I'm getting alot of "get key failed from google" and reading around it seem like the node i use is out of date with the new Google tts changes. 
So wanted to know is this could maybe replace it.

**Comment by ncpierson** [comment]
Yes, this library should be able to be used as a replacement for [google-tts](https://github.com/zlargon/google-tts). Though, it is missing some features such as the "slow" flag.

The biggest difference is that this library returns a `Buffer` full of the mp3 audio data, and google-tts returns a URL.

**Comment by JuniorGamingTime** [comment]
How would I install it? I'm using docker for nodered. And the mp3 shouldn't be an issue hopefully

**Comment by ncpierson** [comment]
You should be able to install it the same way that you installed `google-tts`. Assuming you are using npm or yarn:

```
npm install ncpierson/google-translate-tts
```

or

```
yarn add ncpierson/google-translate-tts
```

**Comment by JuniorGamingTime** [comment]
I tried installing it and it doesn't show up in the pallet (tried both and restarted too)

**Comment by ncpierson** [comment]
Ah, sorry, I'm not familiar with Node Red. It looks like me (or someone) would need to publish this package to Node Red.

I now see your Issue filed in the original google tts package: https://github.com/DeanCording/node-red-contrib-google-tts/issues/7

I'll see what I can do about node red.

**Comment by JuniorGamingTime** [comment]
That would be amazing. I use it alot for my streams for a few things, and we've missed the fun with had with tts. Thanks alot in advance

**Comment by ncpierson** [comment]
Hey @JuniorGamingTime , I just added this library to Node RED. Could you try it out and let me know if it is working for you?

**Comment by ncpierson** [comment]
Closing this issue since it seems to be working now.

**Comment by JuniorGamingTime** [comment]
Sorry to reopen a old issues but seems like the TTS node is not working at all this time. i get no errors or anything now.
Nothing from the last setup has changed, it just stopped working like 2 days ago.

**Comment by ncpierson** [comment]
Hi @JuniorGamingTime , this is a known issue. It's not specific to NodeRED. Google changed the voice parameter to accept different values, and it broke the library.

**Comment by JuniorGamingTime** [comment]
Are you working on an update? If its possible. Ill try an look for an alternative. I use this node alot on my streams so wanna try and get something working on the mean time.
